refactor: use argocd-git-ask-pass to pass git credentials to git/kustomize
alexmt/argo-cd pull request #4
Opened 2022-02-11 02:28 UTC by alexmt

Signed-off-by: Alexander Matyushentsev <AMatyushentsev@gmail.com>

In order to provide git credentials to Kustomize Argo CD sets `GIT_ASKPASS=git-ask-pass.sh` env variable so that git clone call `git-ask-pass.sh`  for credentials. The `git-ask-pass.sh` needs to get credentials somewhere so we also set `GIT_USERNAME` and `GIT_PASSWORD`  env variables. The problem is that `GIT_USERNAME` and `GIT_PASSWORD` also available to kustomize and user can leverage kustomize config map generator to just print env variables.

**Fix:**

I think we agreed that it is not safe to have any secret in env variable or file, because one way or another almost all config tools provide a way to read file/env variable. But we can assume config management tool does not allow user to run any custom binary. So proposing following solution:

* introduce `argocd-git-ask-pass` binary and new, localhost-only endpoint in repo-server
* during manifests generation repo server generates uuid, associate it with git credentials and fork/exec config management tool with GIT_ASKPASS='argocd-git-ask-pass <uuid>'
* git executes argocd-git-ask-pass <uuid> , then argocd-git-ask-pass calls send uuid to new repo-server endpoint and receives associated credentials
* once manifest generation is completed repo-server forget about uuid and associated credentials

2022-02-11 21:34 UTC, leoluz reviewed
As we discussed, it would be interesting to add an additional layer of security by changing the  `askPassServer - askPassClient` communication to use gRPC instead of plain HTTP. Doing so, will greatly increase the complexity to exploit kustomize/helm to invoke gRPC requests dynamically.

2022-02-11 23:01 UTC, crenshaw-dev requested changes
Should we make the askpass command its own binary? There's a lot of code in the argocd binary. I don't feel great about providing a path to invoke that file, even if there's no easy way to change the execution path away from just providing a credential.

I think it also makes sense to make an additional binary since no human user should ever need to invoke that command.

2022-02-14 20:36 UTC, jessesuen commented on cmd/argocd-git-ask-pass/commands/argocd_git_ask_pass.go
> +				errors.CheckError(fmt.Errorf("ARGOCD_GIT_ASKPASS_ID is not set"))
I suggest we call this `ARGOCD_GIT_ASKPASS_NONCE` instead of `ID` to better describe the intent/usage of this.

2022-02-15 22:11 UTC, alexmt commented on cmd/argocd-git-ask-pass/commands/argocd_git_ask_pass.go
> +				errors.CheckError(fmt.Errorf("ARGOCD_GIT_ASKPASS_ID is not set"))
good suggestion. done

2022-02-15 22:18 UTC, alexmt commented
@crenshaw-dev we package all binaries into one to reduce the size of argocd image: golang packages whole runtime into each binary and all our binaries are sharing the same libraries. So packaging everything into 1 binary allows us to have 1 ~120 mb binary instead of 5 binaries 100mb ~ 110mb each. 

The `argocd` CLI behaves differently based on binary name. See https://github.com/argoproj/argo-cd/blob/master/cmd/main.go . E.g. is CLI is called via symlink named `argocd-git-ask-pass` then CLI act as `argocd-git-ask-pass` binary. So for the end users it looks like we have lots of separate binaries.

2022-02-15 22:19 UTC, alexmt commented
@leoluz switched from http server to grpc.

2022-02-15 22:22 UTC, crenshaw-dev commented
@alexmt makes sense. I'm sure one binary is fine then. I'm still a bit curious though. If the askpass binary were super simple (didn't include all the extra libraries), would it still be ~100mb? Is the runtime that large?

2022-02-18 16:56 UTC, closed without merging